const fs=require('fs'),vm=require('vm'),assert=require('assert');
const elements=new Map();const doc={body:{dataset:{}},createElement(){return {setAttribute(){},textContent:''};},getElementById(id){if(!elements.has(id))elements.set(id,{style:{},appendChild(){},focus(){},scrollIntoView(){},innerHTML:'',textContent:''});return elements.get(id)},querySelectorAll(){return []}};
const store=new Map();const storage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>{store.set(k,String(v));},removeItem:k=>{store.delete(k);}};
const globals=()=>({document:doc,location:{search:'?demo=1'},URLSearchParams,sessionStorage:storage,crypto:require('crypto').webcrypto,window:{scrollTo(){}},setTimeout,clearTimeout,AbortController,console});
const src=fs.readFileSync(require('path').join(__dirname,'../app.js'),'utf8');const ctx=vm.createContext(globals());vm.runInContext(src,ctx);const run=s=>vm.runInContext(s,ctx);
(async()=>{
for(const p of ['f','m']){run(`persona='${p}';`);for(let i=0;i<=14;i++){run(`step=${i};questionIndex=0;render()`);assert(elements.get('screen').innerHTML.includes('error'));assert(!elements.get('screen').innerHTML.includes('undefined'));}}
run('step=1');assert(run('validate()'));run("answers.성별='여성'");assert.equal(run('validate()'),'');run('step=2');assert(run('validate()'));run("answers.주선자='m';persona='m';step=4;Object.assign(answers,{이름:'테스트',출생연도:'1997',키:'163',생활권:'잠실',직업:'기획',학교:'고려대',MBTI:'ENFP'})");assert.equal(run('validate()'),'');run("questionIndex=2;answers.키='999'");assert(run('validate()'));run("questionIndex=7;answers.키='163';answers.MBTI='oops'");assert(run('validate()'));run("answers.MBTI='ENFP';step=5;questionIndex=0;Object.assign(answers,{취미:'요가',음주:'가끔',흡연:'안 피워'})");assert.equal(run('validate()'),'');run("Object.assign(answers,{이상형:'대화',제외조건:'흡연',중요조건:'연락'});step=9;render()");assert(elements.get('screen').innerHTML.includes('흡연'));run("answers.중요조건='연락과 소비';step=8;render();step=9;render()");assert(elements.get('screen').innerHTML.includes('연락과 소비'));run('step=11');assert(run('validate()'));run('photos=[{},{},{}]');assert.equal(run('validate()'),'');run("step=12;questionIndex=3;answers.유입경로='인스타';answers.연락처='123'");assert(run('validate()'));run("answers.연락처='01012345678'");assert.equal(run('validate()'),'');run('step=14');assert(run('validate()'));run('answers.개인정보동의=true;answers.프로필소개동의=INTRO_CHOICES[1]');run("answers.이메일='hello@example.com'");await run('submit()');assert.equal(run('view'),'complete');assert(elements.get('screen').innerHTML.includes('1~2일'));assert(elements.get('screen').innerHTML.includes('접수 완료'));assert.equal(run('answers.성별'),'여성');assert.equal(run('answers.주선자'),'m');run('submitted=false');
run("view='complete';render()");assert(!elements.get('screen').innerHTML.includes('확인 상태 미리보기'));assert(!elements.get('nav').innerHTML.includes('id="status"'));assert(elements.get('nav').innerHTML.includes('내 정보 보기'));

run("answers.이름='<img src=x onerror=alert(1)>';view='profile';render()");assert(!elements.get('screen').innerHTML.includes('<img src=x'));assert(elements.get('screen').innerHTML.includes('&lt;img'));
run("view='form';step=9;questionIndex=0;render()");
assert.equal((elements.get('screen').innerHTML.match(/data-review=/g)||[]).length,16);
for(const label of ['이름','피하고 싶은 사람','학교 · 전공','쉬는 날 하는 일','만나고 싶은 사람'])assert(elements.get('screen').innerHTML.includes(label));
run("returnToReview=true;step=4;questionIndex=2;answers.키='999'");await run('next()');assert.equal(run('step'),4);
run("answers.키='170'");await run('next()');assert.equal(run('step'),9);assert.equal(run('returnToReview'),false);assert(elements.get('screen').innerHTML.includes('170cm'));
console.log('PASS: 16 complete review bubbles, invalid edit blocked, valid edit returns to review.');
for(const [st,ix,key,optional] of [[4,5,'같은회사제외',false],[5,1,'음주',false],[5,2,'흡연',false],[5,3,'종교',true],[10,0,'연봉',true],[12,0,'유입경로',false]]){
 run(`view='form';step=${st};questionIndex=${ix};answers['${key}']='';returnToReview=false`);
 await run('next()');assert.equal(run('step'),st);assert.equal(run('questionIndex'),ix);
 if(optional){await run('next(true)');assert(run('step')!==st||run('questionIndex')!==ix);}
}
console.log('PASS: all six empty choice questions blocked; explicit optional skip allowed.');
run("view='form';step=4;questionIndex=5;answers.같은회사제외='';render()");{const html=elements.get('screen').innerHTML;assert(html.includes('data-key="같은회사제외"')&&html.includes('<textarea')&&!html.includes('data-value="피하고 싶어"')&&html.includes('data-value="상관없어"'));assert(html.includes('회사명이나 학교명은 정확히 적어줘.'));}assert(run('validate()'));run("answers.같은회사제외='○○회사, ○○대학교'");assert.equal(run('validate()'),'');assert(fs.readFileSync(require('path').join(__dirname,'../server/Code.gs'),'utf8').includes("'같은회사제외'"));
console.log('PASS: exclusion accepts free text or the no-preference shortcut, shown in review, and mapped on the server.');
for(const [st,ix] of [[4,0],[4,3],[4,4],[4,6],[5,0],[6,0],[7,0],[8,0],[12,3]]){run(`view='form';step=${st};questionIndex=${ix};render()`);const placeholders=[...elements.get('screen').innerHTML.matchAll(/placeholder="([^"]*)"/g)].map(m=>m[1]).join(' ');assert(placeholders,`no placeholder at step ${st}/${ix}`);for(const pii of ['함다인','네이버','경영학과','잠실','판교','01012345678'])assert(!placeholders.includes(pii),`placeholder leaks ${pii} at step ${st}/${ix}`);}
run("view='form';step=4;questionIndex=0;render()");assert(elements.get('screen').innerHTML.includes('placeholder="홍길동"'));
console.log('PASS: placeholders contain no person-like data; generic example name in use.');
assert.equal(run("sendsOnEnter({key:'Enter',shiftKey:false,isComposing:false,keyCode:13})"),true);assert.equal(run("sendsOnEnter({key:'Enter',shiftKey:true,isComposing:false,keyCode:13})"),false);assert.equal(run("sendsOnEnter({key:'Enter',shiftKey:false,isComposing:true,keyCode:229})"),false);assert.equal(run("sendsOnEnter({key:'Enter',shiftKey:false,isComposing:false,keyCode:229})"),false);assert.equal(run("sendsOnEnter({key:'a',shiftKey:false,isComposing:false,keyCode:65})"),false);
run("view='form';step=6;questionIndex=0;render()");assert(elements.get('screen').innerHTML.includes('<textarea') && elements.get('screen').innerHTML.includes('enterkeyhint="send"'));
console.log('PASS: Enter sends, Shift+Enter and IME composition do not; textarea carries enterkeyhint=send.');
for(const [st,ix] of [[4,6],[10,1],[12,3]]){run(`view='form';step=${st};questionIndex=${ix};render()`);const html=elements.get('screen').innerHTML;assert(!html.includes('자동 질문으로 얘기를 모으고'),'chat still opens with the automation notice');assert(!html.includes('말하기 불편하면'),'optional hint still repeated');assert(html.includes('chat-date'));}
assert(elements.get('screen').innerHTML.includes('추가로 확인할 내용이 있을 때 연락할게'));assert(!elements.get('brand').innerHTML.includes('운영자가 나중에 확인'));assert(!elements.get('brand').innerHTML.includes('촉 좋은 인싸 언니')&&!elements.get('brand').innerHTML.includes('발 넓은 마당발 형'));
console.log('PASS: chat notices trimmed; contact purpose folded into the question bubble; header shows only host identity.');
run("view='form';step=0;questionIndex=0;render()");{const html=elements.get('screen').innerHTML;assert.equal((html.match(/class="intro-slide"/g)||[]).length,3);for(const key of ['고대생','네트워크','부탁하는 부담 없이','내 프라이버시','프로필'])assert(html.includes(key),`intro slide missing ${key}`);}
console.log('PASS: 3 intro slides name the KU-made network, comfortable introductions and profile privacy.');
for(const p of ['f','m']){run(`view='host';profilePersona='${p}';render()`);const html=elements.get('screen').innerHTML;for(const key of ['host-facts','<dt>소속</dt>','<dt>주선 경험</dt>','<dt>이런 사람</dt>','class="bubble"','직접 확인해요'])assert(html.includes(key),`host profile missing ${key}`);assert(!html.includes('undefined'));const nav=elements.get('nav').innerHTML;assert(nav.includes('id="hostList"')&&nav.includes(`data-persona="${p}"`)&&nav.includes('과 대화하기'));}
console.log('PASS: host profile renders labelled facts, message preview, list-return and start-chat actions for both hosts.');
// #35 intentionally expands the welcome and permission copy. Browser tests check wrapping at 320px; other messages retain a short-copy guard.
{const long=[];const check=(where)=>{for(const m of elements.get('screen').innerHTML.matchAll(/<div class="bubble">([^<]*)<\/div>/g)){const t=m[1];if(t.length>(run("view")==="complete"?160:[3,6,7,11,13,14].includes(run("step"))?90:40)||(t.includes('\n')&&run('step')!==13))long.push(where+': '+t);}};for(const p of ['f','m']){run(`persona='${p}';view='form';returnToReview=false`);for(let s=3;s<=14;s++){const n=run(`QUESTIONS[${s}]?QUESTIONS[${s}].length:1`);for(let i=0;i<n;i++){run(`step=${s};questionIndex=${i};render()`);check(`${p} ${s}/${i}`);}}run("view='complete';render()");check(p+' complete');}assert.deepEqual(long,[],'unexpectedly long bubbles:\n'+long.join('\n'));run("view='form'");}
console.log('PASS: host bubbles across both personas and result states respect their copy length guard with no hard line breaks.');
assert.equal(run("checkPhoto({name:'a.jpg',type:'image/jpeg',size:1000})"),'');assert.equal(run("photoType({name:'x.PNG',type:''})"),'image/png');assert(run("checkPhoto({name:'a.gif',type:'image/gif',size:1000})").includes('JPG, PNG, WebP'));assert(run("checkPhoto({name:'IMG_1.HEIC',type:'image/heic',size:1000})").includes('HEIC'));assert.equal(run("checkPhoto({name:'big.png',type:'image/png',size:60*1024*1024})"),'','size must not be rejected up front');assert(run('PHOTO_LIMIT.edge>0&&PHOTO_LIMIT.bytes<=5*1024*1024&&typeof shrinkPhoto==="function"'));run("view='form';step=11;questionIndex=0;render()");assert(!elements.get('screen').innerHTML.includes('5MB'));
run("view='form';step=11;questionIndex=0;returnToReview=false;photos=[{},{}]");assert(run('validate()').includes('1장 더'));run('photos=[{},{},{},{},{},{}]');assert(run('validate()').includes('지워줘'));run('photos=[{},{},{}]');assert.equal(run('validate()'),'');
{const gs=fs.readFileSync(require('path').join(__dirname,'../server/Code.gs'),'utf8');assert(gs.includes("error.expose?error.message")&&gs.includes("reject_('사진은 3~5장 필요합니다.')")&&gs.includes('5*1024*1024')&&gs.includes('jpeg|png|webp'));}
console.log('PASS: photo checks name the file and reason (type, HEIC); no user-facing size limit (large photos are shrunk client-side under the server cap); count messages say how many more; server exposes its own validation messages.');
// #14: per-host sessions
run("submitted=false;editing=false;busy=false;returnToReview=false;for(const k in sessions)delete sessions[k];view='form';step=2;questionIndex=0;render()");
run("startChat('f')");assert.equal(run('step'),3);assert.equal(run('history.length'),0);await run('next()');run("answers.이름='홍길동'");await run('next()');assert.deepEqual(run('[step,questionIndex,history.length]'),[4,1,2]);
run("startChat('m')");assert.deepEqual(run('[step,questionIndex,history.length,answers.주선자]'),[3,0,0,'m']);await run('next()');assert.equal(run('step'),4);
run("startChat('f')");assert.deepEqual(run('[step,questionIndex,history.length,answers.주선자]'),[4,1,2,'f']);
run("startChat('m')");assert.deepEqual(run('[step,questionIndex,history.length]'),[4,0,1]);
run("step=2;questionIndex=0;render();startChat('f')");assert.deepEqual(run('[step,questionIndex,history.length]'),[4,1,2]);
run("editing=true;startChat('f')");assert.deepEqual(run('[step,history.length]'),[3,0]);run('editing=false');
console.log('PASS: each host keeps its own bubbles and position across switches; edit flow still restarts.');
// #15: independent answers per host, sessionStorage persistence, progress on the list, post-submit lock
run("editing=false;submitted=false;returnToReview=false;sessions={};view='form';step=2;render()");
run("startChat('f')");await run('next()');run("answers.이름='홍길동'");await run('next()');
run("startChat('m')");assert.equal(run("answers.이름||''"),'');assert.equal(run('answers.성별'),'여성');assert.equal(run('answers.주선자'),'m');await run('next()');
run("startChat('f')");assert.equal(run('answers.이름'),'홍길동');
{const saved=JSON.parse(store.get('chinchinso-sessions-demo'));assert.equal(saved.성별,'여성');assert.equal(saved.sessions.f.answers.이름,'홍길동');assert.deepEqual([saved.sessions.f.step,saved.sessions.f.questionIndex],[4,1]);assert(saved.sessions.m&&!('photos' in saved.sessions.f));}
run("step=2;questionIndex=0;render()");{const html=elements.get('screen').innerHTML;assert(html.includes('진행 중 · 2/27'),'f progress');assert(html.includes('진행 중 · 1/27'),'m progress');}
{const ctx2=vm.createContext(globals());vm.runInContext(src,ctx2);const r=s=>vm.runInContext(s,ctx2);assert.equal(r('step'),2);assert.equal(r('base.성별'),'여성');assert.deepEqual(r('[sessions.f.step,sessions.f.questionIndex,sessions.f.photos.length,sessions.f.answers.이름]'),[4,1,0,'홍길동']);r("startChat('f')");assert.deepEqual(r('[step,questionIndex,history.length,answers.이름,answers.주선자]'),[4,1,2,'홍길동','f']);}
{store.set('chinchinso-sessions-demo',JSON.stringify({성별:'남성',sessions:{m:{history:[{step:3,index:0},{step:4,index:0},{step:11,index:0}],step:12,questionIndex:1,answers:{이름:'테스트'}},f:{history:[{step:3,index:0},{step:4,index:0},{step:4,index:1}],step:4,questionIndex:0,answers:{}}}}));const ctx3=vm.createContext(globals());vm.runInContext(src,ctx3);const r=s=>vm.runInContext(s,ctx3);assert.deepEqual(r('[sessions.m.step,sessions.m.questionIndex,sessions.m.history.length]'),[11,0,2],'photo step after reload');assert.deepEqual(r('[sessions.f.step,sessions.f.questionIndex]'),[9,0],'review after interrupted edit');}
run("sessions.f.photos=[{},{},{}];startChat('f');step=14;answers.프로필소개동의=INTRO_CHOICES[1];answers.개인정보동의=true;answers.출생연도='1997';returnToReview=false");run("answers.이메일='hello@example.com'");await run('submit()');assert.equal(run('view'),'complete');assert.deepEqual(run('Object.keys(sessions)'),[]);assert.equal(store.has('chinchinso-sessions-demo'),false);
run("view='form';step=5;render()");assert.equal(run('view'),'complete');run("startChat('m')");assert.equal(run('view'),'complete');run("view='form';step=2;render()");assert.equal(run('view'),'complete');
run("editing=true;view='form';step=0;questionIndex=0;history=[];render()");assert.equal(run('view'),'form');run("startChat('f')");assert.deepEqual(run('[view,step,answers.이름]'),['form',3,'홍길동']);run("step=13;returnToReview=false");run("answers.이메일='hello@example.com'");await run('submit()');assert.deepEqual(run('[view,editing,submitted]'),['complete',false,true]);
run('submitted=false;editing=false');
console.log('PASS: answers are per host, drafts persist and restore (photos re-requested, interrupted edit resumes at review), list shows progress, submit forgets drafts and locks the chat, explicit edit flow still works.');
// #31: service name, start buttons, host list
{const read=f=>fs.readFileSync(require('path').join(__dirname,'..',f),'utf8');for(const f of ['index.html','demo.html','app.js'])assert(read(f).includes('찐친소')&&!read(f).includes('친친소'),f+' still says 친친소');for(const f of ['assets/host-f.svg','assets/host-m.svg'])assert(read(f).startsWith('<svg'));assert(read('index.html').includes('app.js?v=28'));}
run("sessions={};base.성별='';answers=base;view='form';step=0;questionIndex=0;render()");{const nav=elements.get('nav').innerHTML;assert(nav.includes('>전 여자예요<')&&nav.includes('>전 남자예요<'));assert(nav.includes('data-start="여성"')&&nav.includes('data-start="남성"'));assert(!nav.includes('성별을 선택하면'));assert(elements.get('screen').innerHTML.includes('찐친소'));}
run("base.성별='여성';step=2;render()");{const html=elements.get('screen').innerHTML;assert(html.includes('주선을 좋아하는')&&html.includes('편한 사람을 골라 얘기해봐요'));assert(html.includes('서울대 · 연구원'));assert(!html.includes('각종 모임 100회+')&&!html.includes('고려대 · 직장인'));assert(html.includes('assets/host-f.svg')&&html.includes('assets/host-m.svg'));assert(!html.includes('data-host='),'profile detail entry must be blocked');assert.equal((html.match(/data-persona=/g)||[]).length,2);assert(!/class="contact-avatar [fm]"[^>]*>[가-힣]</.test(html),'letter avatar left');}
run("startChat('m')");assert(elements.get('brand').innerHTML.includes('assets/host-m.svg'));assert(elements.get('screen').innerHTML.includes('class="message-avatar" aria-hidden="true"><img class="avatar-img" src="assets/host-m.svg'));
run("sessions={};answers=base;view='form';step=2;render()");
console.log('PASS: brand is 찐친소 everywhere; start buttons read 전 여자예요/전 남자예요 without the helper line; list shows the new banner, character avatars, 정진 as 서울대 · 연구원, and no profile-detail entry.');
ctx.fetch=async()=>({ok:true,json:async()=>({ok:true})});await assert.rejects(run("request({})"),/지원하지/);ctx.fetch=async()=>({ok:false});await assert.rejects(run('request({})'),/연결하지/);
console.log('PASS: 30 step/persona renders; validation; summary preservation; independent gender/persona; demo submit; completion without status controls; HTML escaping; legacy response and network failure handling.');
new vm.Script(fs.readFileSync(require('path').join(__dirname,'../server/Code.gs'),'utf8'));console.log('PASS: Apps Script syntax');
})().catch(e=>{console.error(e);process.exit(1)});
